name: Tests Frontend
run-name: ${{ github.actor }} is testing out frontend 🚀
on:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/github-actions-frontend.yml'

jobs:
  Test-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up frontend pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: frontend/package.json
          run_install: false

      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml 
      
      - name: install Frontend dependencies
        run: make deps-front

      - name: build Angular frontend
        run: make build-front

      # - name: run frontend unit tests
      #   run: cd frontend && pnpm run test
